### ISSUE TITLE
Unable to import with Django 1.7b4 and Python 3.4

### ISSUE THREAD

**Issue by gourneau** [shymonk/django-datatable#7]
After installing this and including it in my INSTALLED_APPS tuple, I get this error when I try to run a dev server. 

Is this just not Python 3 compatible yet?

```
c:\code\Tools\MSAnalysis\massspec>python manage.py runserver 0.0.0.0:80
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python34\lib\site-packages\django-1.7b4-py3.4.egg\django\core\management\__init__.py", line 4
27, in execute_from_command_line
    utility.execute()
  File "C:\Python34\lib\site-packages\django-1.7b4-py3.4.egg\django\core\management\__init__.py", line 3
91, in execute
    django.setup()
  File "C:\Python34\lib\site-packages\django-1.7b4-py3.4.egg\django\__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python34\lib\site-packages\django-1.7b4-py3.4.egg\django\apps\registry.py", line 85, in popul
ate
    app_config = AppConfig.create(entry)
  File "C:\Python34\lib\site-packages\django-1.7b4-py3.4.egg\django\apps\config.py", line 87, in create
    module = import_module(entry)
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\django_table-1.0.0-py3.4.egg\table\__init__.py", line 5, in <module>
ImportError: No module named 'tables'
```

**Comment by gourneau** [comment]
thanks a lot!
